export default [
  {
    name: "Momohjimoh Hashidu",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Computer Science",
    level: "300 Level",
    gender: "Male",
    image: "hashidu.jpg",
  },

  {
    name: "Aka'aba Musa",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Computer Engineering",
    level: "300 Level",
    gender: "Male",
    image: "musa.jpg",
  },
  {
    name: "Abdulsalam Muhammed-Jamiu",
    state: "Kogi",
    institution: "FUT Minna",
    course: "Mathematics",
    level: "Graduate",
    gender: "Male",
    image: "photo.png",
  },
  {
    name: "Abdullahi Faridah",
    state: "FCT",
    institution: "Ahmadu Bello University",
    course: "Insurance",
    level: "300 Level",
    gender: "Female",
    image: "faridah.png",
  },
  {
    name: "Obans Unoiza Habibat",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Botani",
    level: "Graduated",
    gender: "Female",
    image: "beebah.JPG",
  },
  {
    name: "Aminu Harisu",
    state: "Jigawa",
    institution: "Ahmadu Bello University",
    course: "Computer Science",
    level: "300 Level",
    gender: "Male",
    image: "aminu.jpg",
  },

  {
    name: "Salihu Abass Onimisi",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Mathematics",
    level: "300 Level",
    gender: "Male",
    image: "abass.jpg",
  },
];
