export default [
  {
    name: "Abdulsalam Muhammed-Jamiu",
    state: "Kogi",
    institution: "FUT Minna",
    course: "Mathematics",
    level: "Graduate",
    gender: "Male",
    image: "photo.png",
  },
  {
    name: "Musa Kazim",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Computer Engineering",
    level: "300 Level",
    gender: "Male",
    image: "musa.jpg",
  },
  {
    name: "Momohjimoh Hashidu",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Computer Science",
    level: "300 Level",
    gender: "Male",
    image: "hashidu.jpg",
  },
  // {
  //   name: "AbdulSalam Onimis",
  //   state: "Kogi",
  //   institution: "FUT Minna",
  //   course: "Micro Biology",
  //   level: "200 Level",
  //   gender: "Male",
  //   image: "hashid.jpg",
  // },
  {
    name: "Obans Unoiza Habibat",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Botani",
    level: "Graduated",
    gender: "Female",
    image: "beebah.JPG",
  },
  {
    name: "Aminu Harisu",
    state: "Jigawa",
    institution: "Ahmadu Bello University",
    course: "Computer Science",
    level: "300 Level",
    gender: "Male",
    image: "aminu.jpg",
  },

  {
    name: "Salihu Abass Onimisi",
    state: "Kogi",
    institution: "Ahmadu Bello University",
    course: "Mathematics",
    level: "300 Level",
    gender: "Male",
    image: "abass.jpg",
  },
];
